export { InAIAuthClient } from "./client";
export { InAIAuthError } from "@inai-dev/shared";
export {
  buildAuthObjectFromToken,
  buildAuthObjectFromClaims,
  getClaimsFromToken,
  isTokenExpired,
} from "./tokens";

// Re-export types for convenience
export type {
  InAIAuthConfig,
  AuthObject,
  ServerAuthObject,
  ProtectedAuthObject,
  UserResource,
  PlatformUserResource,
  SessionResource,
  OrganizationResource,
  ApplicationResource,
  EnvironmentResource,
  ApplicationStats,
  ApiKeyResource,
  RoleResource,
  PermissionResource,
  PlatformMemberResource,
  PlatformInvitationResource,
  PaginatedResult,
  JWTClaims,
  LoginParams,
  LoginResult,
  MFAChallengeParams,
  TokenPair,
  SignInResult,
  SignUpResult,
  InAIAuthErrorBody,
  WebhookResource,
  EmailTemplateResource,
  AuditLogResource,
  AppSessionResource,
  OrganizationMemberResource,
  InvitationResource,
  MfaSetupResponse,
  BackupCodesResponse,
  ImportUsersResult,
} from "@inai-dev/types";
